name: LOCAT CD

on:
  # main에 merge 될 때만 진행
  push:
    branches: ["main" ]

jobs:
  locat-CD:
    runs-on: ubuntu-latest

    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: Dockerfile
          push: true
          # 이미지를 두 가지 방식으로 접근하기 위함. 최신 버전 + 특정 커밋 버전 - 추적 및 롤백 용도
          tags: |
            ${{ secrets.DOCKER_REPO }}/prod:latest
            ${{ secrets.DOCKER_REPO }}/prod:${{ github.sha }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        id: deploy-prod
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.KEY_PROD }}
          envs: GITHUB_SHA
          script: |
            sudo docker rm -f locat-server
            sudo docker pull ${{ secrets.DOCKER_REPO }}/prod:latest
            sudo docker run -d \
              --name locat-server \
              --env-file .env \
              -p 80:80 \
              ${{ secrets.DOCKER_REPO }}/prod:latest
            docker image prune -f