name: PR Reminder

on:
  schedule:
    - cron: '0 8 * * *' # KST 17시(UTC 8시)에 실행

jobs:
  pr-reminder:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Run PR reminder
        uses: SeongHo5/pr-reminder@latest
        with:
          platform: discord
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          remind-time: 24

